### ISSUE TITLE
HTTP redirection loop

### ISSUE THREAD

**Issue by johnjohndoe** [open-uri-redirections/open_uri_redirections#9]
For [this download](http://apps.london.ca/OpenData/ShapeFiles_Zipped/Tree_Inventory_Public.zip) I run into the following "HTTP redirection loop" error:

```
/home/johnjohndoe/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:231:in `open_loop': 
    HTTP redirection loop: http://apps.london.ca/uniquesig87fdc01fb86ce \
    6f0fd235c713015d7d7/uniquesig0/InternalSite/StartApp.asp?resource_id= \
    837A134B9EC24A2197B6AF5745B6CA55&login_type=0&site_name=appstrunk& \
    secure=0&orig_url=http%3a%2f%2fapps.london.ca%2fOpenData%2f \
    ShapeFiles_Zipped%2fTree_Inventory_Public.zip (RuntimeError)

    from /home/johnjohndoe/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
    from /home/johnjohndoe/.rvm/gems/ruby-2.1.0@global/gems/open_uri_redirections-0.1.4/lib/open-uri/redirections_patch.rb:52:in `open_uri'
    from /home/johnjohndoe/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:703:in `open'
...
```

Here is the relevant part of the script that I use:

``` ruby
def http_download_uri(uri, filename)
  pbar = nil
  begin
    uri.open(
          allow_redirections: :all,
          read_timeout: 500,
          content_length_proc: lambda { |t|
          if t && 0 < t
            pbar = ProgressBar.new("...", t)
            pbar.file_transfer_mode
          end
          },
          progress_proc: lambda {|s|
            pbar.set s if pbar
          }) do |file|
      open filename, 'w' do |io|
        file.each_line do |line|
          io.write line
        end
      end
    end
  rescue => e
    case e
    when OpenURI::HTTPError
      puts "HTTPError: '#{e}' for #{uri}"
    when Zlib::BufError
      puts "Zlib::BufError: '#{e}' for #{uri}"
    else
      raise e
    end
  end
end
```

**Comment by johnjohndoe** [comment]
Finally, a workaround was given to me. Find it in [this bugreport](https://bugs.ruby-lang.org/issues/11322).

**Comment by jaimeiniesta** [comment]
Good to know, thanks @johnjohndoe 

You can also consider using other alternatives like Faraday that have more support for following redirections, setting a limit to them, using cookies, etc. See this example:

https://github.com/jaimeiniesta/metainspector/blob/master/lib/meta_inspector/request.rb#L54

**Comment by johnjohndoe** [comment]
Thanks, I will consider that. I did not stumble over [Faraday](https://github.com/lostisland/faraday) before.
